runtime: nodejs20
service: api
instance_class: F2  # instance class affects cost and performance
env_variables:
  NODE_ENV: production
  PORT: 8080

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 4